import Link from 'next/link'
import Head from 'next/head'


export const Layout=({title, children})=> {
  return (
    <div>
        <Head>
            <title>{title ? title+' PrimeInvest':title }</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main >
            {children}
        </main>
    </div>
  )
}
