import Link from 'next/link'
import Head from 'next/head'
import Header from './Header'
import Footer from './Footer'


export const Layout=({title, children})=> {
  return (
    <>
        <Head>
            <title>{title ? title+' PrimeInvest':title }</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header></Header>
            <main id='mainprincipal'>
             {children} 
            </main>
        <Footer></Footer>
    </>
  )
}
